default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "nikodyring_portfolio-db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "nikodyring_portfolio") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: nikodyring_portfolio_development

test:
  <<: *default
  database: nikodyring_portfolio_test

production:
  <<: *default
  database: nikodyring_portfolio_production

queue:
  <<: *default
  database: nikodyring_portfolio_production
  migrations_paths: db/queue_migrate

cable:
  <<: *default
  database: nikodyring_portfolio_production
  migrations_paths: db/cable_migrate
