# Name of your application. Used to uniquely configure containers.
service: nikodyring_portfolio

# Name of the container image.
image: nikodyring/nikodyring_portfolio

# Deploy to these servers.
servers:
  web:
    - 188.245.219.60

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: nikodyring.dev
  healthcheck: 
    interval: 3
    path: /up
    timeout: 5

# Credentials for your image host.
registry:
  server: ghcr.io
  username: nikodyring
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh: 
  user: app
  keys: ["~/.ssh/id_ed25519"]

builder:
  arch: amd64

env:
  clear:
    POSTGRES_USER: nikodyring_portfolio
    POSTGRES_DB: nikodyring_portfolio_production
    DB_HOST: nikodyring_portfolio-db
    REDIS_URL: redis://nikodyring_portfolio-redis:6379/0
    JOB_CONCURRENCY: 5
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:18
    host: 188.245.219.60
    port: "5433:5432"
    env:
      clear:
        POSTGRES_USER: nikodyring_portfolio
        POSTGRES_DB: nikodyring_portfolio_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - "nikodyring_portfolio_db_data:/var/lib/postgresql"
  redis:
    image: redis:7.0
    host: 188.245.219.60
    directories:
      - "nikodyring_portfolio_redis_data:/data"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"