# Name of your application. Used to uniquely configure containers.
service: nikodyring_portfolio

# Name of the container image.
image: nikodyring/nikodyring_portfolio

# Deploy to these servers.
servers:
  web:
    - 188.245.219.60
  job:
    - 188.245.219.60
    cmd: bundle exec sidekiq -C config/sidekiq.yml

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: nikodyring.dev

# Credentials for your image host.
registry:
  server: ghcr.io
  username: nikodyring
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets)
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: false
    JOB_CONCURRENCY: 5
    DB_HOST: db
    REDIS_HOST: redis
    POSTGRES_USER: nikodyring_portfolio
    POSTGRES_DB: nikodyring_portfolio_production

# Aliases
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Persistent storage
volumes:
  - "nikodyring_portfolio_storage:/rails/storage"
  - "nikodyring_portfolio_db_data:/var/lib/postgresql/data"
  - "nikodyring_portfolio_redis_data:/data"

# Bridge fingerprinted assets
asset_path: /rails/public/assets

# Image builder
builder:
  arch: amd64

# Accessories: PostgreSQL and Redis
accessories:
  db:
    image: postgres:18
    host: db
    port: 5432
    env:
      clear:
        POSTGRES_USER: nikodyring_portfolio
        POSTGRES_DB: nikodyring_portfolio_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - nikodyring_portfolio_db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2
    host: redis
    directories:
      - nikodyring_portfolio_redis_data:/data
